### ISSUE TITLE
公众号分类

### ISSUE THREAD

**Issue by hellodword** [hellodword/wechat-feeds#1021]
> We can't make this file beautiful and searchable because it's too large.

观察到 [`list.csv`](https://github.com/hellodword/wechat-feeds/blob/e20de2f/list.csv) 已经大到无法被 github 预览（可预览的状态参见 [`list.csv - 16b82d3`](https://github.com/hellodword/wechat-feeds/blob/16b82d3/list.csv)），觉得需要处理一下，刚好也应该考虑一下分类了

此 issue 讨论若干问题：

- csv 这个文件是否需要更换格式？
- 如何对公众号进行分类？

**Comment by hemind** [comment]
可以考虑列一个公众号分类表，让添加的人来选择分类，比如 list.csv 文件每行开头添加一项分类编号

**Comment by testsetestset** [comment]
希望能直接根据「帐号主体」认证情况来分类，比如，区分：
政府、事业单位、企业（可再细分企业类型）、其他组织（可详细到机构类型）、个人这种

**Comment by testsetestset** [comment]
另外，感觉 list.csv 内 description 意义不大，要不要考虑去掉 description？

**Comment by hellodword** [comment]
> 另外，感觉 list.csv 内 description 意义不大，要不要考虑去掉 description？

这个我也考虑过，实际上只有 bizid 也没意义，改的话要改 CI 要改程序，那样处理完会十分依赖展示页，可能需要社区有人对页面进行访问体验方面的优化以及 SEO 等等，后面会考虑。

你暂时可以留空，只关注 bizid，例如 `社会扶贫,MzI1NTQxODA4NA==,` 或 `社会扶贫,MzI1NTQxODA4NA==,""`

**Comment by hellodword** [comment]
> 可以考虑列一个公众号分类表，让添加的人来选择分类，比如 list.csv 文件每行开头添加一项分类编号

的确倾向于继续保持用 csv 文件，因为 csv 对非编程人员比较友好（相对于 YAML），github 有预览 （相对于 INI），同时不预览的状态也很直观（相对于 JSON）

单独用一列来标记分类而不是用文件来分类确实是个好思路，不出意外会用这个方案，需要改 CI 和程序，等有空了我会实现一下。

**Comment by hellodword** [comment]
> 希望能直接根据「帐号主体」认证情况来分类，比如，区分：
> 政府、事业单位、企业（可再细分企业类型）、其他组织（可详细到机构类型）、个人这种

可能倾向于用一些已有的榜单分类

- [newrank](https://www.newrank.cn/public/info/list.html)
- [sogou](https://weixin.sogou.com/)

**Comment by hemind** [comment]
弄个二级分类，如果能加 tag 就更好了

- category number, name, bizid, "description", "tag1, tag2, tag3..."
