### ISSUE TITLE
影像

### ISSUE THREAD

**Issue by moyao404** [hellodword/wechat-feeds#1034]
https://mp.weixin.qq.com/s/Af-fVcokANbRZRYqqwvO_w

**Comment by hellodword** [comment]
页面似乎有变动，你可以学习一下手动抓取，也可以等我修复好

**Comment by hellodword** [comment]
`医学影像园,MzIxODE2MTA1OQ==,"国内知名医学影像专业学术网站，致力学术交流，全国最大的医学影像交流平台。"`

[RSS链接](https://github.com/hellodword/wechat-feeds/raw/feeds/MzIxODE2MTA1OQ==.xml) | [国内链接](https://gitee.com/BlogZ/wechat-feeds/raw/feeds/MzIxODE2MTA1OQ==.xml)

**Comment by hellodword** [comment]
好了，你可以去按照文档提 pr 了
