### ISSUE TITLE
关于全文 RSS

### ISSUE THREAD

**Issue by hellodword** [hellodword/wechat-feeds#1497]
其实全文 RSS 在技术上没有多少难点，顶多就是解析几类页面

但是据我所知，访问 `mp.weixin.qq.com` 会限制 IP，一个 IP 一个时间段里我记得只能访问 4000 余次，不知有无可以提供绕过方法或者贡献资源的？

**Comment by hellodword** [comment]
以及微信图片跨域问题，大概也是需要资源的，这方面继续利用 jsdelivr 可能有点不道德。

体验差成本低的可以是 [cloudflare-cors-anywhere](https://github.com/Zibri/cloudflare-cors-anywhere)，体验好的可能需要服务器和 CDN

总之 help wanted :)

**Comment by weimanMK** [comment]
收费

**Comment by hellodword** [comment]
> 收费

收费是不会收费的，

首先这类服务是没办法保证稳定的，例如未来在对抗的过程中成本提高到无法承受就只能停止了

另外尽管有很多同类收费服务，但实际上收费会有法律风险

**Comment by keithnull** [comment]
其实很多 RSS 阅读器都已经提供了下载全文的功能，而且这样子还能避免服务器 IP 访问过于频繁被微信拉黑，所以应该没啥必要在此提供全文 RSS。

**Comment by faustliang** [comment]
> 其实很多 RSS 阅读器都已经提供了下载全文的功能，而且这样子还能避免服务器 IP 访问过于频繁被微信拉黑，所以应该没啥必要在此提供全文 RSS。

现在多数情况用电报看的，rss阅读器只用过feedly，电报要便捷一些，可是微信抓取的只有标题部分🤣

**Comment by ohblue** [comment]
私有化部署就没这烦恼了

**Comment by howie6879** [comment]
> 微信图片跨域问题

Hi: @hellodword 

这个问题是否可以试试利用CSDN的微信图片转发
比如微信原图：https://mmbiz.qpic.cn/mmbiz_jpg/YRBRJvZXcIUW8lFIEBesXJW7CRuFvwhKwBiaYHT342EFpG7R7gchYYkla1JdcLKm7rksObYdZZ23hmswbUeIpcw/640

csdn对应地址就是：https://ss.csdn.net/p?+微信url

https://ss.csdn.net/p?https://mmbiz.qpic.cn/mmbiz_jpg/YRBRJvZXcIUW8lFIEBesXJW7CRuFvwhKwBiaYHT342EFpG7R7gchYYkla1JdcLKm7rksObYdZZ23hmswbUeIpcw/640

**Comment by TonyRL** [comment]
> 微信图片跨域问题

You can also consider https://images.weserv.nl (cloudflare-backed) or Photon CDN (from WordPress).

**Comment by hellodword** [comment]
各位抱歉，想来想去还是不碰全文比较好

参考 #2408 

在此关闭本 issue

**Comment by god-hu** [comment]
如果能通过rsshub，那应该是可以用rsshub全文获取的方式。
