### ISSUE TITLE
关于更新速度

### ISSUE THREAD

**Issue by hellodword** [hellodword/wechat-feeds#1498]
代码有点脏，打了很多补丁，订阅越来越多跑得越来越慢。。。

一直也没有精力去优化，准备抽空重构一下 #TODO

**Comment by hellodword** [comment]
同时我可能需要抽空稍微学习一下 RSS 的 RFC 了。。。

**Comment by hellodword** [comment]
处理了一下，放弃了获取文章详情，太影响速度，反正缩略图也简介也替代不了全文，不如考虑全文方案。

**Comment by hellodword** [comment]
如今速度是之前的近十倍

**Comment by hellodword** [comment]
如今速度是之前的二十倍，解决了一个严重 BUG，尝试提高更新频率

**Comment by emengweb** [comment]
爆赞！👍👍👍
