### ISSUE TITLE
如果能有一个排序的功能就好了.

### ISSUE THREAD

**Issue by chaleaoch** [hellodword/wechat-feeds#1562]
几千个公众号 没有识别能力了...
如果根据订阅数排个序...就方便多了.

**Comment by hellodword** [comment]
> 根据订阅数

这个可能不行，原则上不希望记录使用者的数据，包括提到的图标功能引发的 [隐私风险](https://github.com/hellodword/wechat-feeds#%E9%9A%90%E7%A7%81%E9%A3%8E%E9%99%A9) 也在思考如何规避。

> 几千个公众号 没有识别能力了

只是提供 RSS 订阅功能，不是很希望做成榜单类型，是主动订阅，而不是创造一个新的推荐服务，榜单服务可以用新榜等产品获取想要的公众号，然后来这里搜索或者新增

> 排个序...就方便多了

这个确实， #1021 也是为此而讨论，只不过我不会前端，等待有缘人。。。

**Comment by chaleaoch** [comment]
thanks 那我关掉了.

**Comment by hemind** [comment]
可以考虑把最近几篇文章的阅读数（点赞数、在看数）平均一下，列出来做个参考？虽然这些数据不一定反应了文章质量。。
