### ISSUE TITLE
列表页搜索词的大小写问题

### ISSUE THREAD

**Issue by hemind** [hellodword/wechat-feeds#1570]
目前需要大小写完全正确，不便于检索。如 theCrag 公众号，输入 thecrag 则搜索不到。

列表页: https://wechat.privacyhide.com/

**Comment by hellodword** [comment]
fixed in [89d0009](https://github.com/hellodword/wechat-feeds/commit/89d0009b4f7de7f28752cb6ef96ccdfc99b8ff06)

谢谢
