### ISSUE TITLE
FreshRss貌似无法正确识别

### ISSUE THREAD

**Issue by stefaneliu** [hellodword/wechat-feeds#1703]
大佬，我碰到了问题。我以前用的是ttrss，将xml地址导入软件后可以正确识别并正常更新。但是改用FreshRss后，该软件就无法识别xml地址了。
FreshRss带有一个检查源有效性的工具。随便找个xml地址检查，可以得到以下信息：
[https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgitee.com%2FBlogZ%2Fwechat-feeds%2Fraw%2Ffeeds%2FMjM5MDE4NTk4MA%3D%3D.xml](url)
反正就是报错。
我不大懂上面写了一些啥？能帮忙看看是怎么回事吗？谢谢！

**Comment by hellodword** [comment]
MIME type 的问题，简单说就是这些 rss 订阅工具需要返回的 header 里面的 type 是 xml，而现在的方案返回的会是 text，我几乎不能在现有方案之上解决，但我会抽空给出一个变通的方案：用 cloudflare workers 之类的免费服务修改返回的 header。

**Comment by stefaneliu** [comment]
好的，谢谢。辛苦大佬了。

**Comment by hellodword** [comment]
简单实现了个，代码见 [proxy](https://github.com/hellodword/wechat-feeds/tree/42000f80acb4c7f006dda0a7053f699d0f7173bb)。

用法很简单，例如原先的 feed 地址是 `https://github.com/hellodword/wechat-feeds/raw/feeds/Mzg2ODAyNTgyMQ==.xml`，只需要在前面加上 `https://proxy.privacyhide.com/` 就可以了，也就是：

`https://proxy.privacyhide.com/https://github.com/hellodword/wechat-feeds/raw/feeds/Mzg2ODAyNTgyMQ==.xml`

托管在 `workers.dev` 上，每天数万次请求额度，也可以自己部署。

你可以试下

**Comment by stefaneliu** [comment]
感谢大佬，目测可行。

**Comment by hellodword** [comment]
> 感谢大佬，目测可行。。
> 
> update: 貌似我用我自己的地址就不对。
> 比如：我这个订阅网址：https://gitee.com/BlogZ/wechat-feeds/raw/feeds/MjM5NTE2NDM5Mg==.xml
> 在前面加上：https://proxy.privacyhide.com/ 后
> 就是： https://proxy.privacyhide.com/https://gitee.com/BlogZ/wechat-feeds/raw/feeds/MjM5NTE2NDM5Mg==.xml
> 但是，这个网址打开后出现了error 1101。
> 订阅失败。。。。
> 是网址的问题吗？
> 谢谢！

我屏蔽了 gitee，因为这个服务本身就是国外的节点，所以没有国内加速一说，所以只允许以 `https://github.com/hellodword/wechat-feeds/raw/feeds/` 开头的 feed 使用

**Comment by stefaneliu** [comment]
多谢大佬，这次行了！感谢！

**Comment by hellodword** [comment]
OK，这个 proxy 服务最近使用遇到任何问题在这里回复，等一段时间没有问题我就更新到 README 中。
