### ISSUE TITLE
list.csv的第一列名称完全凭良信, 没有进行验证.

### ISSUE THREAD

**Issue by chaleaoch** [hellodword/wechat-feeds#1930]
如图, merge 成功了.

![image](https://user-images.githubusercontent.com/11831441/113511052-74108100-9590-11eb-9d24-23bb2848a1c5.png)

**Comment by hellodword** [comment]
是的，具体展示页也不参考它，一切都只以 bizid 为准，因为考虑到公众号也会改名字，我虽然可以矫正数据，也会搞乱 commit，所以暂时还是没办法考虑它。
