### ISSUE TITLE
订阅列表图

### ISSUE THREAD

**Issue by xunzhi026** [hellodword/wechat-feeds#2093]
打扰作者了，请问订阅列表这里的图片能实现同步么
![Screenshot_2021-04-12-02-00-33-990_com tencent mm](https://user-images.githubusercontent.com/82331574/114315745-e0f8bd80-9b32-11eb-9fb8-65620cf36135.jpg)
![Screenshot_2021-04-12-02-00-35-614_com tencent mm](https://user-images.githubusercontent.com/82331574/114315750-e524db00-9b32-11eb-93ac-553b622955f7.jpg)

**Comment by hellodword** [comment]
提供过一段时间，出于一些考虑在 [这里](https://github.com/hellodword/wechat-feeds/issues/1498#issuecomment-798382447) 去掉了，比如你可以试一下 [这个](https://github.com/hellodword/wechat-feeds/raw/01ca71c1dfcf99571bc123a59845e41cc0f571c5/MzA3MzYzNjMyMA%3D%3D.xml) （注意只是测试，这个链接不会更新）

后面考虑的可能还是全文 RSS，有全文 RSS 了自然有这些缩略图了，具体讨论&进展见 #1497

**Comment by xunzhi026** [comment]
感谢您的回复！
