### ISSUE TITLE
文本限制展示问题

### ISSUE THREAD

**Issue by howie6879** [hellodword/wechat-feeds#2117]
如访问：https://gitee.com/BlogZ/wechat-feeds/raw/feeds/MzA5NDc1NzQ4MA==.xml

会出现：根据相关法律政策,该内容无法显示

**Comment by hellodword** [comment]
不可抗力，附一张网上看到的图

![](https://user-images.githubusercontent.com/46193371/114644924-06d8ba80-9d0b-11eb-927f-351eab7de7c1.jpeg)

**Comment by hellodword** [comment]
既然遇到了，考虑移除 gitee 支持，或者在文档和页面上加个提示
