### ISSUE TITLE
RSS订阅输出中的author能不能改成公众号的名字，

### ISSUE THREAD

**Issue by lluke2** [hellodword/wechat-feeds#214]
如题，

![image](https://user-images.githubusercontent.com/70134605/98882995-7fbbb800-24c8-11eb-8649-030faf473001.png)

我大概说的就是图中author的部分。要是我没说明白，那就算了吧。我对这些东西不是很了解。

非常感谢作者

**Comment by hellodword** [comment]
图中这个是整个 feed 的 author，一般订阅工具不会展示的吧，至少不该在单篇更新上展示。

你应该是指每个 item 的 author，那个我留空了，因为我没有获取文章具体的作者，而公众号文章的 author 不一定是公众号自身，可能是转载或者是其他作者，这个需求和 **提供全文** 属于同一范畴，没有想到降低成本的办法所以暂时不会考虑获取。

[这就算一个 item](https://github.com/hellodword/wechat-feeds/blob/b08a17b44d885bb38fb4b34ab5005b9aebc3a4de/MjM5MjAzODU2MA%3D%3D.xml#L9-L15)

具体用到的库代码在 [这里](https://github.com/gorilla/feeds/blob/6f6e20dd3953594cd869cf981fb806440685cd21/feed.go#L32-L45)

仍有疑问可 reopen
