### ISSUE TITLE
轻芒杂志已停服！！！

### ISSUE THREAD

**Issue by labulaka521** [hellodword/wechat-feeds#2408]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/24547356/117599761-1964d900-b17d-11eb-8c68-7bcd630490c9.png">

**Comment by cod1ingcoding** [comment]
轻芒真好用，可惜，唉··   数据太封闭了，不好多方权衡

**Comment by gitkeniwo** [comment]
即刻，轻芒，这种模式是真的没法做下去。真的好烦微信公众号呐，但偏偏某几个还不错的信息源都只有公众号一个平台。

**Comment by hellodword** [comment]
顺势移除了 gitee
