### ISSUE TITLE
请教一下您关于重复推送的问题

### ISSUE THREAD

**Issue by Pudding12345** [hellodword/wechat-feeds#2701]
我在知网上订阅了一些期刊，发现他们都有共同的问题——在整点大量推送重复词条。
本人编程小白，目前作出以下推测：即cnki在固定时间推送数额恒定的词条，因为期刊内容有限故将其用过往词条补充完整。
问题1：是否是这种原因，如果不是是什么原因造成
问题2：有什么解决措施
希望能得到您的解答。万分感谢。

**Comment by hellodword** [comment]
https://www.w3schools.com/xml/rss_tag_guid.asp
