### ISSUE TITLE
ttrss始终无法订阅

### ISSUE THREAD

**Issue by 276562578** [hellodword/wechat-feeds#2736]
ttrss的服务器可以访问订阅的网址，但ttrss添加订阅时始终超时，求教

**Comment by 276562578** [comment]
好像是访问不了githubusercontent.com的问题，无解啊

**Comment by 276562578** [comment]
所以能否将订阅链接放到您主页上呢？文件应该也不会很大

**Comment by hellodword** [comment]
托管在 github pages 上，每月有流量限制，而且原本有国内镜像但我因为一些原因取消了，所以实际上是有意为之

**Comment by 276562578** [comment]
哭了 那就没办法了是吧

**Comment by hellodword** [comment]
> 那就没办法了是吧

可以考虑用一些服务中转

会编程：cloudflare workers、serverless、传统反代
不会编程：可以找一些现成的服务，例如 [`7ed.net`](https://www.7ed.net/gra/) （仅作举例），比如源 `https://github.com/hellodword/wechat-feeds/raw/feeds/MzA5NTYzMzAyNQ==.xml` 实际上会跳转到 `https://raw.githubusercontent.com/hellodword/wechat-feeds/feeds/MzA5NTYzMzAyNQ==.xml`，按照 7ED 所说换成 `https://raw.githubusercontents.com/hellodword/wechat-feeds/feeds/MzA5NTYzMzAyNQ==.xml`

**Comment by hellodword** [comment]
但现成的服务是否有缓存问题我是不确定的，如果不在意缓存时间，实际上 jsdelivr 也可以，总之这是项目之外的问题范畴了。

**Comment by 276562578** [comment]
牛！我想的是我提供个服务器，然后把项目部署上，不过这个7ed就够了。
