### ISSUE TITLE
请求生成的xml中加入author

### ISSUE THREAD

**Issue by 276562578** [hellodword/wechat-feeds#2738]
我使用feedme来看rss，然后发现每一条中在主页界面不显示来源，是因为title没有加`![CDATA[ xxxxxxx ]]`吗？
举个例子，这个xml就可以显示来源

\<rss version="2.0">
\<channel>
\<title>
\<![CDATA[ M-Team - TP Torrents ]]>
\</title>
\<link>https://kp.m-team.cc</link>
\<description>
\<![CDATA[ Latest torrents from M-Team - TP - Working ]]>
\</description>
\<image>
\<title>
\<![CDATA[ M-Team - TP Torrents ]]>
\</title>
\<link>https://kp.m-team.cc</link>
\<url>https://kp.m-team.cc/pic/rss_logo.jpg</url>
\</image>
\<language>zh-tw</language>
\<copyright>Copyright (c) M-Team - TP 2012-2021, all rights reserved</copyright>
\<managingEditor>webmaster@m-team.cc (M-Team - TP Admin)</managingEditor>
\<webMaster>webmaster@m-team.cc (M-Team - TP Webmaster)</webMaster>
\<generator>NexusPHP RSS Generator</generator>
\<ttl>60</ttl>
\<lastBuildDate>Sun, 23 May 2021 10:53:08 +0800</lastBuildDate>
\<item>

**Comment by hellodword** [comment]
实话说我对 RSS 的标准一直没有深究，用的是 [gorilla/feeds](https://github.com/gorilla/feeds)，的确是年久失修，go 似乎也没有什么 rss generator 的轮子

**Comment by hellodword** [comment]
feedme + inoreader 用 RSSHUB 的 [源](https://rsshub.app/cgtn/opinions) 也不显示
