### ISSUE TITLE
推送封面图片问题

### ISSUE THREAD

**Issue by cry0824** [hellodword/wechat-feeds#2851]
大佬您好，我想请问一下有没有什么办法可以加上推送的封面图片？
如下第一张图是rsshub上直接订阅的，第二张图是通过wechat-feeds订阅的
谢谢！
![5ebbd1f3e1b1783e5463dc8ae210918](https://user-images.githubusercontent.com/76474355/120076022-451d1400-c0d6-11eb-9c52-85b25ddfd4fa.jpg)
![03eb7abd5f517af94c5a96a0a0bdd61](https://user-images.githubusercontent.com/76474355/120076024-46e6d780-c0d6-11eb-9014-84980b99a332.jpg)

**Comment by hellodword** [comment]
#1497
