### ISSUE TITLE
流利说设计团队

### ISSUE THREAD

**Issue by 9Panda3** [hellodword/wechat-feeds#296]
https://mp.weixin.qq.com/s/ltgeo2BIyqPQ9CCrO5oOVg

**Comment by 9Panda3** [comment]
目前的RSS链接还没有生效

**Comment by hellodword** [comment]
> 目前的RSS链接还没有生效

你可能还没有提交过这个公众号

https://github.com/hellodword/wechat-feeds/pulls?q=is%3Apr+author%3A9Panda3+


这里是辅助查询 bizid 的工具，不会自动提交的
