### ISSUE TITLE
某个 RSS 一直 404

### ISSUE THREAD

**Issue by testsetestset** [hellodword/wechat-feeds#3456]
有些奇怪，「中信建投点金财富,Mzg4NTMyMTQwNg==,""」这个 URL 页面一直是 404，但后续一些公众号 URL 内容均正常
（先不论这堆荐股公众号是否爬虫、占用名额问题）

**Comment by hellodword** [comment]
大概是检测失效号的代码有个逻辑没处理好，没检测出来

https://github.com/hellodword/wechat-feeds/tree/main/check-transfer

每日检测结果在这里 https://github.com/hellodword/wechat-feeds/issues/2387#issuecomment-new

**Comment by hellodword** [comment]
我有空修复一下

**Comment by hellodword** [comment]
简单修复了下检测代码，details.json 有空再修复
