### ISSUE TITLE
有人故意占用资源

### ISSUE THREAD

**Issue by jeukou** [hellodword/wechat-feeds#3485]
向手工一小时抄录两万个公众号的手速大神致敬！
我发现有些PR一次提交上百个公众号，绝大部分都没什么用，怀疑是weress这类网站的利益方给项目灌水！
马上项目就达到10000个了，也就是说很快项目就无法新增公众号了
请问作者有什么后续想法吗

**Comment by hellodword** [comment]
也不用这么揣测，真要是同为做技术的没必要这么提交的，我更倾向于认为这群人将本项目当爬虫用了。

> 马上项目就达到10000个了，也就是说很快项目就无法新增公众号了

也不是不能调节上限，只是暂定 10000，后面考虑下吧

> 请问作者有什么后续想法吗

很简单，整理出来删掉并禁止这些用户提交（改下代码就行了）即可，个人公益的小众项目，各位 RSS 爱好者开心即可，没必要在意这些人的

**Comment by airyland** [comment]
发现了这个项目，进来看看，就看到 @jeukou 的恶意揣测。
如果你拼错的名字是 WeRSS 的话，我是该项目的维护者，我至今从未在当前 Repo 提交任何代码。

避免广告嫌疑和避免争论，这条评论我会自己删掉，发出来只是为了告知你，你这莫名其妙的揣测很影响心情。

**Comment by hellodword** [comment]
@airyland 淡定...

话说 we-extract 真不错，本来想着直接拿来用能省很多事了，可惜现在我不敢提供全文 RSS 了😅

**Comment by fghshunzi** [comment]
提高上限、限制提交频率和每次的数量
