### ISSUE TITLE
讨论一下本项目的上限

### ISSUE THREAD

**Issue by hellodword** [hellodword/wechat-feeds#3556]
本项目暂定上限是 10000 个，目前已经接近，而这么快接近的原因主要是最近被提交了大量的荐股公众号

具体讨论及我的态度见 https://github.com/hellodword/wechat-feeds/issues/3485#issuecomment-855905787

所以接下来大致有三种处理方式，
1. 到 10000 个即停止新增；
2. 提升上限，比如改为 20000 个；
3. 移除这类 pr，增加（提交 pr 的）黑名单机制。

各位同好可以在此讨论一下

**Comment by hellodword** [comment]
https://github.com/hellodword/wechat-feeds/commit/0dd38bb2c6bebaadd4832a7d5a5a4d3898235a20 暂且将上限提高到了 20000，但本 issue 仍待讨论

**Comment by testsetestset** [comment]
1. 上限 10000 or 20000 均可接受，感谢楼主提供此项目；
2. 希望移除荐股类 PR，并设置一些限制（近期被频繁提交大量荐票号时，还把我已合并完成的公众号删除掉；同时有些 RSS 工具可以做到内容抓取并自动转发，此项目及荐股内容，有可能被利用在黑灰地带）；
3. 有段时间我习惯将看到的公众号都加一下 RSS，但有部分是营销号类，内容质量不高，以后可以挑出来删除掉释放名额

**Comment by hellodword** [comment]
> 还把我已合并完成的公众号删除掉

这是怎么做到的？是哪个 pr？能找到吗？理论上 bot 不会 merge 有删除操作的 pr

**Comment by testsetestset** [comment]
> > 还把我已合并完成的公众号删除掉
> 
> 这是怎么做到的？是哪个 pr？能找到吗？理论上 bot 不会 merge 有删除操作的 pr

#2958 #2964 
怀疑是我提交第一个 PR 并完成合并期间，他也在频繁提交 PR 导致我的公众号被删？

**Comment by hellodword** [comment]
@testsetestset  那感觉这是个严重 BUG，我先 hide 一下

**Comment by hellodword** [comment]
没有 force push，还有这样的操作，感觉是 github 的锅了

**Comment by testsetestset** [comment]
看了一小部分荐股号内容，
部分公众号名义是 A，但实际内容确实荐股；
还有部分公众号内容几乎完全一致，时间点、文章内容一模一样

**Comment by ymfsing** [comment]
在数量上，我觉得保持10000个比较好，持续增加会是风险增大。超过增加建议采用审核或投票进行。
关于股票、区块链交易相关，特别是短时间大量增加的pr，建议移除，很可能是用于黑产。
我查了一下contributors，有几个人近十天增加了500-700多个，且多数与金融有关，这种明显不是正常人使用的。

**Comment by hellodword** [comment]
> 看了一小部分荐股号内容，
> 部分公众号名义是 A，但实际内容确实荐股；
> 还有部分公众号内容几乎完全一致，时间点、文章内容一模一样

应该可以根据 pr 来，各位如果有空可以统计一下，发到这里或者 gitter 聊天群组，我有空再给加一个黑名单工单，将这些 ID 拉黑

**Comment by hellodword** [comment]
> 在数量上，我觉得保持10000个比较好，持续增加会是风险增大。超过增加建议采用审核或投票进行。
> 关于股票、区块链交易、房产等相关，特别是短时间大量增加的pr，建议移除，很可能是用于黑产。
> 我查了一下contributors，有几个人近十天增加了500-700多个，且多数与金融有关，这种明显不是正常使用的。

多人审核应该会很有效，但有点难操作，我自己没有时间来处理，不然我也不会专门搞个 merge bot 了，大家似乎也没有建立社区的想法——毕竟是一个闭源服务；

那几个 contributors 肯定是要送进黑名单的

**Comment by testsetestset** [comment]
希望移除/拉黑荐股 PR，还有个原因：现在每次编辑 list.csv 加载时间变长，也会浪费大家时间

**Comment by hellodword** [comment]
> 希望移除/拉黑荐股 PR，还有个原因：现在每次编辑 list.csv 加载时间变长，也会浪费大家时间

这个即使没有他们，也是个待解决的问题 #1021

考虑分割成若干个 csv，比如 list01.csv list02.csv ...

比如满 3000 个就移到新的 csv，而只编辑 list.csv，这样编辑的时候就不会失去预览

**Comment by ymfsing** [comment]
> 多人审核应该会很有效，但有点难操作，我自己没有时间来处理，不然我也不会专门搞个 merge bot 了，大家似乎也没有建立社区的想法——毕竟是一个闭源服务；

感觉不要建立社区会比较好，影响力过大有一定风险，我原本构想的审核是通过issues来实现，还是有一定操作成本

鉴于昨天jd_scripts作者宣布停止更新并移除，还是觉得10000个上限会稍微安全一点

**Comment by caolist** [comment]
个人觉得就设置上限为10000，少即是多，增加审核黑名单机制，有负面影响的坚决不能允许进入榜单。

**Comment by Franklittleboy** [comment]
个人认为增加公众号类型审核这个对于大佬的维护成本太高。觉得限制短期内提交的数量可能更容易操作些，不过也确实容易绕开。
荐股类大量出现个人也觉得不太喜欢，作为一个金融从业者，荐股类公众号多数都是laji。

**Comment by hellodword** [comment]
如果无法修复本项目当前无法更新的状态，则本 issue 失去讨论意义…暂时关闭
