### ISSUE TITLE
这个公众号订阅源的文章时间怎么不对呢？

### ISSUE THREAD

**Issue by qingsongya** [hellodword/wechat-feeds#390]
https://github.com/hellodword/wechat-feeds/raw/feeds/MzI2Mzk4MjM4Mg==.xml

我刚刚使用这个微信公众号rss服务，发现有个公众号的订阅源最新文章的时间与真实不一样，这个是今天早上八点钟的文章，但是订阅源中是昨天晚上的，什么情况呢？

还有，订阅源的图标可以抓取一下公众号中的吗？可以抓取全文吗？

**Comment by hellodword** [comment]
> 这个是今天早上八点钟的文章，但是订阅源中是昨天晚上的

哪一篇？我看一下

> 订阅源的图标可以抓取一下公众号中的吗？

可以发几个有图标的源我看一下字段吗？以及你用来订阅的工具是什么

> 可以抓取全文吗？

全文问题参见 [TODO](https://github.com/hellodword/wechat-feeds/blob/65bcd8a223c25cd96d4d5610771b22c060fd51fb/README.md#todo) 倒数第二条，我也很感兴趣，有好思路可以继续讨论

**Comment by hellodword** [comment]
> 我刚刚使用这个微信公众号rss服务，发现有个公众号的订阅源最新文章的时间与真实不一样，这个是今天早上八点钟的文章，但是订阅源中是昨天晚上的，什么情况呢？

我看了下这个公众号，它每天推送时间都是上午8:30，所以我猜测它是定时发布的，而 feeds 中显示的时间就是微信服务器收到这篇文章的时间。

**Comment by hellodword** [comment]
> 我看了下这个公众号，它每天推送时间都是上午8:30，所以我猜测它是定时发布的，而 feeds 中显示的时间就是微信服务器收到这篇文章的时间。

比如 [这一篇](https://mp.weixin.qq.com/s/Beh1Lgmvtb29HIq2_v9Gpg) ， 8:30 对应的 `1607733000` 在它的网页源码中可以看到，所以其实这和抓取全文可能是同一个范畴的问题

**Comment by hellodword** [comment]
> 可以发几个有图标的源我看一下字段吗？以及你用来订阅的工具是什么

比如我尝试过的订阅工具，它处理图标的办法是利用 duckduckgo 来查询对应域名的 favicon 之类的图标，那这样的话其实不适用于这个项目，因为都是同一个域名。所以应当有一个比较规范的图标处理方案。

**Comment by qingsongya** [comment]
> 可以发几个有图标的源我看一下分区吗？
你看下这个两个吧，我这里feedbro都会显示官方图标的，但是第二个是rsshub转换抓取的，我碰到有个轻芒杂志app用它订阅显示的是rsshub官网的图标，我记得轻芒杂志官方有人解释过什么原因吧，我不记得了。
http://feeds.appinn.com/appinns/
https://rsshub.ioiox.com/x6d
> 以及你用来订阅的工具是什么
我现在喜欢使用chrome浏览器的拓展插件feedbro

**Comment by hellodword** [comment]
> > 可以发几个有图标的源我看一下分区吗？
> 
> 你看下这个两个吧，我这里feedbro都会显示官方图标的，但是第二个是rsshub转换抓取的，我碰到有个轻芒杂志app用它订阅显示的是rsshub官网的图标，我记得轻芒杂志官方有人解释过什么原因吧，我不记得了。
> http://feeds.appinn.com/appinns/
> https://rsshub.ioiox.com/x6d
> 
> > 以及你用来订阅的工具是什么
> 
> 我现在喜欢使用chrome浏览器的拓展插件feedbro

我也用的这个，我举个例子吧：

例如 RSSHub 的 [pixiv 源](https://rsshub.app/pixiv/user/11) 

这是个人页面，理想状况应当是工具显示每个用户的头像，但实际上 feedbro 只会显示 pixiv 的 [favicon](https://www.pixiv.net/favicon.ico)

![image](https://user-images.githubusercontent.com/46193371/101979765-de787b00-3c9a-11eb-9228-de9d058771d7.png)

那如果各种订阅工具都是类似的处理方案，而不能解析指定的 icon/logo 字段，那就只能统一显示一下 `mp.weixin.qq.com` 的 favicon ![favicon.ico](https://mp.weixin.qq.com/favicon.ico)  

这是你需要的效果吗？

**Comment by qingsongya** [comment]
理解了，那就这样吧！谢谢
