### ISSUE TITLE
var biz 末尾漏掉 ==，居然检查通过了

### ISSUE THREAD

**Issue by testsetestset** [hellodword/wechat-feeds#594]
见此 PR：https://github.com/hellodword/wechat-feeds/pull/593

**Comment by hellodword** [comment]
是的，checks 没有办法检测 bizid 是否正确

**Comment by testsetestset** [comment]
那我能直接提交新 PR，把 list.csv 里补上 == 不？

**Comment by hellodword** [comment]
可以，但不会自动合并，因为通不过checks， @ 我来手动合并即可
