### ISSUE TITLE
当某个公众号改名后，xml 里 <title> 能同步更新么

### ISSUE THREAD

**Issue by testsetestset** [hellodword/wechat-feeds#816]
例子如：Bio生物世界 改名为 生物世界，但 xml 的 title 仍然是「Bio生物世界 | wechat-feeds」

**Comment by hellodword** [comment]
是可以做到的，列表页或者说 feeds 分支的 details.json 文件就是更新后的。类似 TODO 中的第五条，有空了我实现一下 main 分支的同步

**Comment by hellodword** [comment]
今天处理了下，等会的下一次更新你可以看一下，而且添加了 description，包括文章图片。

**Comment by testsetestset** [comment]
> 今天处理了下，等会的下一次更新你可以看一下，而且添加了 description，包括文章图片。

辛苦大佬

**Comment by hellodword** [comment]
description 偶尔有问题，会继续修复下，但本 issue 应该是解决了。
