### ISSUE TITLE
gitee上的订阅是不是好几天没更新了

### ISSUE THREAD

**Issue by mxh173** [hellodword/wechat-feeds#842]
RT，用的gitee上的rss订阅链接，好几天没有更新了

**Comment by hellodword** [comment]
的确，服务器同步代码给 gitee 失败了，我看下

**Comment by mxh173** [comment]
> 的确，服务器同步代码给 gitee 失败了，我看下

好的，辛苦了

**Comment by hellodword** [comment]
看了下，目前应该是修复了。

gitee 有大小限制，而且  force push 或者 git gc 似乎都无法消除"历史消耗"，必须清空仓库才行，有点坑，后期看下怎么自动化，目前我可以隔一段时间手动处理下。
